apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: giropops-senhas
  namespace: argocd
spec:
  project: 'default'
  source:
    helm: {}
    repoURL: 'https://github.com/reysonbarros/linuxtips-gitops-argocd.git'
    targetRevision: feat/day2
    path: giropops-senhas/helm
  destination:
    namespace: giropops-senhas
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      selfHeal: true # garante que o cluster esta em sincronia com o repositorio(fonte de verdade), ou seja, o cluster so ira executar o que estiver no repo
    syncOptions:
    - CreateNamespace=true